### ISSUE TITLE
Make the data reusable

### ISSUE THREAD

**Issue by noamtamim** [avishayil/corona-health-statement#1]
Child name, child id, parent name, parent id can be saved for later.

Create a link like 
`https://avishayil.github.io/corona-health-statement/#child_name=NAME&child_id=ID&parent_name=NAME&parent_id=ID`, pre-fill the fields using JavaScript.

**Comment by avishayil** [comment]
Cool! great idea.

**Comment by avishayil** [comment]
I think also documentation on the README side is necessary to move this feature to "Done" properly. I'll find some time to do it.
