### ISSUE TITLE
Feature Highlight

### ISSUE THREAD

**Issue by avishayil** [avishayil/corona-health-statement#8]
This issue is about:
- Finding a component that will allow to highlight new features on the first time a user is entering the app.
- A cookie or another storage mechanism will be used to prevent the notification from being shown to the user again (until the expiration period).

**Comment by OrenMe** [comment]
Hi, really great app, thanks!
Got here from a friend who referred me(@noamtamim :-))
I can suggest https://github.com/fkhadra/react-toastify for toasts and combine it with local storage to get notifications shown once.
I also suggest to add a section for overview of features if anyone wants to come back and revisit them later on.

**Comment by avishayil** [comment]
Thanks @OrenMe ! I'll check the library.
Regarding the overview - can you elaborate more?

**Comment by OrenMe** [comment]
If you are already an app user then you will see the updates when you come back to the site.
If you are a new user than you will not see any notifications(or at least you shouldn't as the UX will be poor as the new user will get all notifications).

* So new user shouldn't see a thing when he first join or he should see a welcome screen maybe.
* On each new visit of existing user if new features were added show a notification and mark it as viewed somehow, so it won't be shown again.
* If user - new or existing - wants to see all previous notifications/feature announcements he can click an icon and see a modal with timeline of new features.

![image](https://user-images.githubusercontent.com/5461862/86929907-0e957e00-c13f-11ea-870e-ec862f0bbcd8.png)
[link](https://excalidraw.com/#json=4813729157873664,C_VkUFUl15-KmO52T_b-Mw)

**Comment by avishayil** [comment]
Awesome! @OrenMe Thanks for the UX tips. I think also about a persistent banner (you can compile and test the pull requested branch). This way we can control whether to show the message. I agree that your UX is more friendly, but it would require some time to implement. I'm not lazy, but this is still a community project.
